### ISSUE TITLE
use cargo workspace

### ISSUE THREAD

**Issue by Ryanmtate** [messari/substreams#54]
The repo contains multiple rust crates, which can be referenced in a top-level `Cargo.toml` [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) file.

**Comment by Ryanmtate** [comment]
It appears bumping the compound-v2 `substreams-ethereum = "~0.2.0"` dependency to `"0.2.2-rc"` causes duplicate definitions in the `comptroller.rs` output. This is preventing the use of a workspace, since it ends up with a build conflict:


```
error: failed to select a version for `substreams-ethereum`.
    ... required by package `substreams-uniswap-v2 v0.1.0 (/Users/ryan/Projects/Messari/substreams/uniswap-v2)`
versions that meet the requirements `^0.2.2-rc` are: 0.2.2-rc.2, 0.2.2-rc.1

all possible versions conflict with previously selected packages.

  previously selected package `substreams-ethereum v0.2.0`
    ... which satisfies dependency `substreams-ethereum = "~0.2.0"` of package `compoundv2-substreams v0.1.0 (/Users/ryan/Projects/Messari/substreams/compound-v2)`

failed to select a version for `substreams-ethereum` which could resolve this conflict
```

Seems there may be some more work within `substreams-ethereum-abigen` to resolve the duplicate code generation within the `comptroller` code gen.

**Comment by Ryanmtate** [comment]
Remove one event to unblock on comptroller within the ABI.

Modify the ABI to remove the shadowed event signature.

**Comment by Ryanmtate** [comment]
NOTE: Streaming fast may need to modify the ABI codegen to handle shadow signatures.

**Comment by 0xbe1** [comment]
love to see more standardization like this
