### ISSUE TITLE
enforce consistent dependencies via inheriting

### ISSUE THREAD

**Issue by 0xbe1** [messari/substreams#70]
currently, whenever substreams-related dependencies upgrade, we go to every substreams folder to update them.

this is not desired at the current stage because:
- we want to enforce standard and consistency
- it is error prone

I propose all substreams should inherit substreams-related dependencies from a common workspace. This is made possible in the latest version of Rust https://betterprogramming.pub/workspace-inheritance-in-rust-65d0bb8f9424

Here's how: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

@this-username-is-taken @Ryanmtate what do you think?

**Comment by Ryanmtate** [comment]
I think this is a good idea-- I had thought the workspace would have picked up the same versions already from the member crates, but I think we need to use the `workspace.dependencies` block explicitly. Nice catch.
