### ISSUE TITLE
ci: add substreams sf api key to github secrets

### ISSUE THREAD

**Issue by Ryanmtate** [messari/substreams#72]
#63 Requires access to a streaming fast auth token: https://substreams.streamingfast.io/reference-and-specs/authentication

CI workflow failing due to:

https://github.com/messari/substreams/actions/runs/3116449123/jobs/5054288102

**Comment by 0xbe1** [comment]
ah i see we can put that key to github secrets

**Comment by this-username-is-taken** [comment]
added `STREAMINGFAST_KEY ` to repo secret
