### ISSUE TITLE
Get rid of src/pb for simplicity

### ISSUE THREAD

**Issue by 0xbe1** [messari/substreams#79]
atm, a substreams with pb/ is structured like this:

```
pb/
- erc721.rs
pb.rs
```

where erc721.rs references generated pb files in target/ while pb.rs simply declare modules in erc721.rs

shall we simply store everything in pb.rs and ditch pb/ totally? @Ryanmtate

**Comment by Ryanmtate** [comment]
If we want to store everything in `pb.rs` we will need to modify the codegen to use scoped modules for versioned imports, e.g.

```rust
// src/pb.rs

pub mod example {
  #[rustfmt::skip]
  #[path = "../target/example.v1.rs"]
  pub mod v1;

  #[rustfmt::skip]
  #[path = "../target/example.v2.rs"]
  pub mod v2;
}
```

What do you think?

**Comment by 0xbe1** [comment]
@Ryanmtate lgtm, i will give it a try

**Comment by this-username-is-taken** [comment]
implemented here: https://github.com/messari/substreams/pull/112
