### ISSUE TITLE
substreams sub command for initiating a new substreams

### ISSUE THREAD

**Issue by Ryanmtate** [messari/substreams#88]
Not sure how much work it is but might be helpful to have something we can use to bootstrap new substreams. Something similar to `graph init` in `graph-cli`: https://github.com/graphprotocol/graph-cli. I will add this in the backlog

_Originally posted by @this-username-is-taken in https://github.com/messari/substreams/issues/86#issuecomment-1263826763_
      

Possibly something like `substreams-init` cmd

**Comment by Ryanmtate** [comment]
We could make a `substreams-init` subcommand

**Comment by this-username-is-taken** [comment]
We can break this down into 3 steps:

- [ ] Simple scaffolder that generates fixed stub code
- [ ] Autogen substream package from ABI
- [ ] Allow user to specify contract during scaffolding, and autogen event mapper from ABI

**Comment by this-username-is-taken** [comment]
see https://github.com/messari/substreams/pull/95
